### ISSUE TITLE
Webmin System stats issue

### ISSUE THREAD

**Issue by ChriZathens** [qooob/authentic-theme#114]
Hello and thanks for this theme!
I am facing an issue... using your theme, Webmin System stats (https://sourceforge.net/projects/webminstats/) does not work. I get the first page where I can select the graph to view, but then, when I click on e.g. cpu the graphs do not show. I am not 100% sure if it is the module's or the theme's issue, so I am posting in both bugtrackers. 
Thanks again! 

Later edit: the picture shows all the themes I have. Just tested and module works fine with all other themes
![untitled](https://cloud.githubusercontent.com/assets/8545172/6348406/f233d7c4-bc27-11e4-9aa1-35a947bfb07e.png)

**Comment by qooob** [comment]
You mean like the spinner is always shown?

**Comment by ChriZathens** [comment]
Yeap, exactly that...
No graphs, just the spinner

**Comment by qooob** [comment]
Alright. I have fixed this issue already in dev build on my computer. It will be available for all in version 10.0.0  within a week or so. 

So far, just double click on the loader to make it go away. ..or press shift two times to do the same.

I hope it will work for you.

Thanks for reporting.

**Comment by ChriZathens** [comment]
Well shift does not work for me, but double clicking did the job..
Thanks!!!

**Comment by ChriZathens** [comment]
Hello and thanks for the new version!
Just checked, though and the issue still remains, unfortunatelly...

**Comment by qooob** [comment]
It's hardly possible, I tested it many time! Clear browser's cache and restart Webmin! If you still see it, please be exact on what you click.

**Comment by ChriZathens** [comment]
I have cleared my cache, but not restarted webmin...
I will do so and report back - thanks!

**Comment by ChriZathens** [comment]
OK, just checked again...
Restarted webmin and tried to access from a machine that had never accessed my webmin before...
Still the same.... 
Mind you, this happens when trying to use Webmin System stats (https://sourceforge.net/projects/webminstats/). I don't know if it happens somewhere else...

**Comment by qooob** [comment]
It happens when you click what? The link on the left, the very first time? Did you have latest WebminStats?

**Comment by ChriZathens** [comment]
Hi, again!!!
Sorry for not being clear... I had actually wrote it in my first post, though... I get the first page where I can select the graph to view, but then, when I click on e.g. cpu the graphs do not show.
Double clicking the loading animation allows me to see the graph.
"webminstats version 2.10 on Ubuntu Linux 12.04 in en language
webminstats is up to date"

**Comment by qooob** [comment]
That I can not reproduce, at least for me, please look:

https://rostovtsev.ru/pub/Screencast_from_03-05-2015_09:39:45_PM.webm

**Comment by ChriZathens** [comment]
Hello!
You did not need to get into such trouble and create a video, lollll
Your support is great, I give you that!!
So we are using the same module version, same webmin version but different OS (doubt if is is relevant, though...)
I logged in with Firefox (never logged in again with FF - I am using Chrome) and the problem remains still... So it must be something else... (If I delete the module and install it again, will I lose the collected data?)
Any more ideas?
Thanks again!

**Comment by qooob** [comment]
Thanks! In case you delete module and it's configuration, then Yes! Configuration is stored in /etc/webmin/webminstats (or somewhere there). You can back up the data, then reinstall the module.. Or just rename `/etc/webmin/webminstats` to something like `/etc/webmin/___webminstats`..

I'm not sure what is happening really. As I tested it in both browsers and it work fine.. Try running Webmin in incognito window (Ctrl+Shift+N in Chrome and see what you get)
