### ISSUE TITLE
Update to 11.01 fails

### ISSUE THREAD

**Issue by codeclinic** [qooob/authentic-theme#146]
If I click the theme update button located on the System Information page, Webmin appears to go through loading the various urls. However when this ends and the System Information page is reloaded, it is still showing the Authentic Theme version as 11.00.

I also tried downloading the update file and then installing this via Webmin Config > Webmin Themes. However this returns an error saying that the gzip file cant be uncompressed(or similar).

Is the file corrupt, or is there some error at my Webmin system?

**Comment by qooob** [comment]
There was a bug at the first 30 minutes of 11.00 it was fixed. It exactly affected updates. It's completely fixed in 11.01. Update manually please: 

https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz

**Comment by codeclinic** [comment]
If i try installing that file I get the following error:

: Failed to gunzip file : 



Ive even deleting the existing Authentic-Theme prior to uploaded the latest version, but still get that same error. Now I dont have Authentic at all. ;-(

**Comment by codeclinic** [comment]
Strange! 

I just installed Authentic-Theme directly directly from the url (rather than uploading it) and all appears to have worked fine.
