### ISSUE TITLE
Problem with dashboard since Webmin 1.780 update

### ISSUE THREAD

**Issue by antoineguilbert** [qooob/authentic-theme#317]
Hello,

I have a problem with my dashboard on Webmin since the last update. All information are unavailable but when I switch to another theme, it's work. 

![capture d ecran 2016-01-01 a 18 15 00](https://cloud.githubusercontent.com/assets/16510381/12071586/f6ab7696-b0b3-11e5-98b6-2b587690571e.png)

Do you know this problem ? 

Thanks and happy new year ! :-)

**Comment by qooob** [comment]
Webmin developer forgot to pull latest version of Authentic Theme. Please update to the latest version of the theme, which is 17.30.

In few hours I will make a patch to support new Filemin stuff in Webmin 1.780.

**Comment by qooob** [comment]
Fixed in 17.31. Please update.

**Comment by antoineguilbert** [comment]
I've updated the theme to 17.31 version and the problem is not fixed. Do you have an idea ?

**Comment by qooob** [comment]
I don't unfortunately but I'll be looking.. Be kind to reboot your server completely to be very sure, ok?

**Comment by antoineguilbert** [comment]
Thanks for your fast answer ! I have completely restarted my server and I also tried to delete and reinstall the theme. Nothing change, dashboard don't work. 

But if I come back to the default theme "Gray Framed Theme", it's ok.

**Comment by 7starsone** [comment]
what OS ?

**Comment by qooob** [comment]
That sounds very weird and more like impossible.

Please post your system specifications (OS, browser), for both server and client computer.

I tested it in Ubuntu, CentOS and Fedora - all is working correctly.

**Comment by antoineguilbert** [comment]
I work on Mac OS 10.11.2 with Safari 9.0.2 and Chrome 47.0.2526. Both browsers have the same problem.

My server is an VPS at OVH who work with Debian 8 (Jessie). See the attached picture on my Webmin. 

![capture d ecran 2016-01-02 a 00 16 19](https://cloud.githubusercontent.com/assets/16510381/12072586/7a73b0ce-b0e6-11e5-96d6-a9e2cdd0e4a3.png)

**Comment by antoineguilbert** [comment]
Just for you information, it works very well before the update of Webmin that I've done today.

**Comment by qooob** [comment]
1. Did it happen before the upgrade to Webmin 1.780
2. Pay attention, when you go to System Information page and reload it (only right frame) manually do you have this `NaN` appear right away or a moment after?

**Comment by 7starsone** [comment]
another user reports that had issues with 1.780 and Debian 8... something like Webmin didn't auto start anymore and he had to start it by command line..don't know if is related, but just to know..

**Comment by antoineguilbert** [comment]
1. No, it never happen before the upgrade to Webmin 1.780.
2. When I goes to System Information page and if I click on the green button to refresh the right frame, I have the NaN who appear.

**Comment by 7starsone** [comment]
cleared the browser cache/cookies and reloaded ?

**Comment by qooob** [comment]
Not the green button, right click, context menu, reload frame content. Do you get correct values at the very beginning or it's that right away?

**Comment by antoineguilbert** [comment]
@7starsone I have cleared the browser cache/cookies and the problem is already there. I've also tried the private navigation. 

@qooob I've also tried your method but nothing. I've "NaN" just after the refresh, I don't see correct value anytime.

**Comment by qooob** [comment]
Webmin developer says he didn't change anything in this concern. I have very little idea at the moment of why it's happening. I'll test tomorrow.

**Comment by qooob** [comment]
Does the rest of the page loads fully/correctly.

**Comment by qooob** [comment]
Did you install any browser's plugins? Tried on other OSes? Like Linux/Windows/Android?

**Comment by antoineguilbert** [comment]
No, as you can see on the first screenshot, I don't have any information. Not just graphics with CPU, RAM, but all informations on dashboard don't show like :

- Webmin version
- Time on system
- Kernel and CPU

But if I switch to another theme on Webmin, it works like the second screenshot. I test now on different OSes.

**Comment by qooob** [comment]
Also, while being on System Information page, open Notification Slider and click refresh button, anything changes? Errors in console?

**Comment by antoineguilbert** [comment]
Nothing changes when I click on notification slider or refresh button. They are few errors in console, check with the screenshot.

![capture d ecran 2016-01-02 a 00 52 14](https://cloud.githubusercontent.com/assets/16510381/12072650/3135ad40-b0eb-11e5-93bb-c65c8ee846e3.png)

**Comment by qooob** [comment]
I see. Please try other OS, not iOS. Like Chrome in Linuxor Windows at last.

**Comment by 7starsone** [comment]
http://www.troyhunt.com/2015/10/how-to-break-your-site-with-content.html

**Comment by 7starsone** [comment]
"The answer is to use both child-src and frame-src"

**Comment by antoineguilbert** [comment]
Same problem on Android with Chrome and iOS with Safari/Chrome. Now, I try with Chrome on Windows 10.

**Comment by antoineguilbert** [comment]
The problem is there in Chrome on Windows 10.

**Comment by 7starsone** [comment]
other errors in console?

**Comment by antoineguilbert** [comment]
No errors in the console in Chrome on Windows 10 and Mac OS. I get these errors only with Safari I think. So it may not be the source of the problem ?

**Comment by 7starsone** [comment]
well, with Safari there's an issue for sure... on Windows 10/Chrome it works if you choose another theme?

**Comment by antoineguilbert** [comment]
Yes, it works on Chrome when I choose another theme. To sum up, the problem is the same on Windows/Mac/iOS/Android with Chrome/Safari.

**Comment by 7starsone** [comment]
I think there's a problem with the specific combination 1.780/Debian 8/Authentic Theme...Ilia could understand why...now I need to go. Happy 2016! ;-)

**Comment by qooob** [comment]
I wasn't lazy and installed fourth OS for debugging - Debian 8. I _could **not**_ reproduce your issue.

Here is the [Video Screencast](https://rostovtsev.ru/pub/src/authentic/17.xx/issue-317/Screencast_from_02-01-16_14:32:27.webm)

Please make sure to check your local settings, it's not the theme's bug for sure.

Also, I would like to see your video screencast with opened console!?

I will close the issue for now.

**Comment by 7starsone** [comment]
so, your theme has even an internal cache system? Is that cleared when you reboot the server? May be that his issue?

**Comment by qooob** [comment]
No, it's not cleared upon reboot. :P

**Comment by antoineguilbert** [comment]
Hey guys ! I've completly reinstalled Webmin tonight and now, dashboard works very well ! Maybe a crash during the upgrade of Webmin.

Many thanks !
