### ISSUE TITLE
Mailman  windows impossible to manage

### ISSUE THREAD

**Issue by aqueos** [qooob/authentic-theme#632]
hi,

  The theme lock the window when you go into the mailman management then authenticate on a mailling list and click to manage users of the list it show them, then scroll to the end of the list by its own and lock the window. You cannot scroll the window or change anything in it.

this link: https://xxxxxxxxxxxxxxxxxxx:10000/virtualmin-mailman/admin.cgi/cbp/members

the FF console show:

Content Security Policy: La directive « frame-src » est obsolète. Veuillez utiliser la directive « child-src » à la place.
Error: Syntax error, unrecognized expression: #aguilera.didier%40orange.fr_unsub

best regards,
Aqueos.

**Comment by qooob** [comment]
Dupe https://github.com/qooob/authentic-theme/issues/613 and it's been fixed in 18.31+.

Make sure to upgrade to Webmin 1.830.

**Comment by aqueos** [comment]
the panel say webmin 1830 and theme is Version 18.31 (December 09, 2016) but i still have the issue.

||/ Name                                                                      Version                                   Architecture                              Description

ii  webmin                                                                    1.830                                     all                                       web-based administration interface for Unix systems

error is in FF console:
Error: Syntax error, unrecognized expression: #webmaster02%40gmail.com_unsub  bundle.min.js:2:13905
	bp</dV.error https://xxxx.myserver.net:10000/unauthenticated/js/bundle.min.js:2:13905
	bp</dV.tokenize https://xxxx.myserver.net:10000/unauthenticated/js/bundle.min.js:2:20018
	bp</dV.select https://xxxx.myserver.net:10000/unauthenticated/js/bundle.min.js:2:22998
	dV https://xxxx.myserver.net:10000/unauthenticated/js/bundle.min.js:2:7551
	.find https://xxxx.myserver.net:10000/unauthenticated/js/bundle.min.js:2:25694
	bv.fn.init https://xxxx.myserver.net:10000/unauthenticated/js/bundle.min.js:2:26197
	bv https://xxxx.myserver.net:10000/unauthenticated/js/bundle.min.js:2:605
	__mcr/< https://xxxx.myserver.net:10000/unauthenticated/js/content.min.js:6:16765
	.each https://xxxx.myserver.net:10000/unauthenticated/js/bundle.min.js:2:2869
	__mcr https://xxxx.myserver.net:10000/unauthenticated/js/content.min.js:6:15155
	<anonyme>


chrome also has the issue.



don't know if this is the veyr same bug or a new one but just so you know.


 i cleared the cache in my browser and in the theme settings but that stay like this. I also tested it at another computer running on ubuntu and the issue is the same (i am fedora).

best regards,
Ghislain

**Comment by qooob** [comment]
Could you try to disable all of your `Extensions` and try again?

**Comment by qooob** [comment]
It's also strange that you're having `*.min.js:2` in your logs. It should be `*.min.js:1831` actually.

**Comment by aqueos** [comment]
in extention all is empty so i dont think i have any. I have made webmin theme cache clear then stop/start webmin. Re open in another browser (opera) then log into mailman from virtualmin and get the same result.

ll /usr/share/webmin/authentic-theme/unauthenticated/js/bundle.min.js
-rw-r--r-- 1 root root 228K déc.  28 00:11 /usr/share/webmin/authentic-theme/unauthenticated/js/bundle.min.js
 
GUEST:root@ :[~]: sha256sum /usr/share/webmin/authentic-theme/unauthenticated/js/bundle.min.js
080c2235b35d8d69ce96e86f2cdc894623d659691b8a3ec6c6c2df00ebf0071d  /usr/share/webmin/authentic-theme/unauthenticated/js/bundle.min.js

**Comment by qooob** [comment]
That is strange. It works on my debug server. Could you maybe record videoscreencast? I'm not sure what is going on.

**Comment by aqueos** [comment]
in extention all is empty so i dont think i have any. I have made webmin theme cache clear then stop/start webmin. Re open in another browser (opera) then log into mailman from virtualmin and get the same result.

ll /usr/share/webmin/authentic-theme/unauthenticated/js/bundle.min.js
-rw-r--r-- 1 root root 228K déc.  28 00:11 /usr/share/webmin/authentic-theme/unauthenticated/js/bundle.min.js
 
GUEST:root@ :[~]: sha256sum /usr/share/webmin/authentic-theme/unauthenticated/js/bundle.min.js
080c2235b35d8d69ce96e86f2cdc894623d659691b8a3ec6c6c2df00ebf0071d  /usr/share/webmin/authentic-theme/unauthenticated/js/bundle.min.js

**Comment by qooob** [comment]
Can you go to _Theme Configuration_ and add to exclusion list not-working module? Screenshot would really help. You can upload it just by dropping then on GitHub window (where you write text.)

**Comment by aqueos** [comment]
uploa fails in github for the screen. Anyway, excluding virtualmin-mailman solved the issue. I tried to update to 1832 but it failed. seems the js error on some of the email adresses

**Comment by qooob** [comment]
What version of the theme are you on? 1831+ updates properly.

**Comment by qooob** [comment]
You can update the theme 18.32 manually or wait for another Webmin update that is coming very soon.

**Comment by aqueos** [comment]
webmin
ii  webmin                      1.830        all          web-based administration interface for Unix systems
ii  webmin-security-updates     4.5          all          Webmin module for 'Virtualmin Package Updates'
ii  webmin-virtual-server       5.05.gpl     all          Webmin module for 'Virtualmin Virtual Servers (GPL)'
ii  webmin-virtual-server-theme 9.0-2        all          Webmin theme 'Virtualmin Framed Theme'
ii  webmin-virtualmin-awstats   5.1          all          Webmin module for 'AWstats Reporting'
ii  webmin-virtualmin-dav       3.8          all          Webmin module for 'Virtualmin DAV'
ii  webmin-virtualmin-htpasswd  2.6          all          Webmin module for 'Virtualmin Protected Directories'
ii  webmin-virtualmin-mailman   6.3          all          Webmin module for 'Virtualmin Mailman Mailing Lists'
ii  webmin-virtualmin-svn       5.1          all          Webmin module for 'Virtualmin Subversion Repositories'


theme:
Version Thème 	Authentic Theme 18.31. Dernière version disponible 18.32  


the link 'update' to 18.32 just spin and do nothing.

,debian jessie all patched installed and up to date, virtual checkconfig is ok too.
