### ISSUE TITLE
Theme: Authentic Theme moving to the next level with 19.00+

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#807]
Hi,

I have just added Authentic Theme 19.00-RC1.

**Comment by qooob** [comment]
To install this beta preview, go to _Webmin/Webmin Configuration/Webmin Themes/Install Theme/From ftp or http URL_, check the radio-button, paste the following link and hit _**Install Theme**_.

```Link
https://github.com/qooob/authentic-theme/releases/download/19.00-beta1/authentic-theme-19.00-beta1.wbt.gz
```

**Comment by 7starsone** [comment]
Hello 😃 
"things that just don't work yet." ...for example?
thanks

**Comment by qooob** [comment]
For example, go to `Webmin/Usermin Configuration` and try hitting `Start/Stop Usermin`. Unless you force reload the content page, it will not work. Same for other bottom submits, like in _Running Processes_, when you go to the process certain id.

For some undiscovered reasons yet, I works only on the first load/once.

**Comment by qooob** [comment]
The other one, when you switch from _Webmin_ to _Virtualmin_, and try hitting the link in the menu, the new background call feature get activated only on the second.

**Comment by 7starsone** [comment]
I think that it should be installed on a "unused/for testing only" VPS at first (if they can)... at the moment I don't own something like that to help and don't have much time to play around with. Anyway, hope you can improve it/make it ready very soon 😉

**Comment by qooob** [comment]
.. definitely not very soon ..

**Comment by qooob** [comment]
I installed it on my production, played around a bit and then went to theme settings to force-update to the latest release. Not a problem at all.

**Comment by sinankizar** [comment]
First help :D
: HTTP/1.1 404 Not Found

**Comment by qooob** [comment]
I updated the link. You can also check Releases section.

**Comment by tpnsolutions** [comment]
So, I decided to deploy the beta theme on one of the servers I exclusively manage, hence no customers would be affected by any bugs or quirks.

Anyways, when you click on "Virtualmin" or "Webmin" tabs in the upper left corner, the "charts" (CPU, Real Memory, and Local Disk Space) don't populate if coming from another task (ex. Edit Virtual Server).

Seems, to get them to render again, you need to click on "System Information" link at the bottom of the left panel, after which clicking "Virtualmin" or "Webmin" will produce the charts again.

Hopefully this helps in your debugging, and development.

Will keep my ear to the ground any other quirks, however so far so good in general.

**Comment by tpnsolutions** [comment]
beta2 reads as "beta1" on the "System Information" page, so I'm not sure if it was installed correctly.

"Time on system" double prints, with first copy linkable, and the second simply being text directly after the first.

Non-Pro user sees a link to "System Statistics" in the left panel,

*** that's just the initial bugs I see immediately after upgrading (though the version issue makes me wonder ***

**Comment by qooob** [comment]
To download newly releasedd _**Authentic Theme RC-1**_ please go to [Releases](https://github.com/qooob/authentic-theme/releases/tag/19.00-RC1).

**Comment by gnadelwartz** [comment]
in my setup only the default webmin modules was working, but e.g. Apache module and all others gave me an error like /usr/libexec/somecgi.cgi..../apache not found. note the 4 dots.

additionally the system timeon dashboard is shown twice

so i reverted to 18.49-8

**Comment by qooob** [comment]
Hi,

Are you behind proxy?

**Comment by gnadelwartz** [comment]
of course 😎

**Comment by Tantawi** [comment]
I have the second issue (system time showing twice on dashboard, one linking to /time and the other beside it in black, none linked), plus:

1- Checking for packages updates by clicking the refresh icon on the dashboard does nothing, no errors in console and no Ajax requests are made.

2- If I click on "All installed packages are up to date" and click on "Refresh available packages" button, it work but the browser moves to "/package-updates/update.cgi?mode=updates&search=&refresh=Refresh+Available+Packages" and the side menu disappears.

3- System -> Software packages -> "Search for package:" does nothing again, no console errors or AJAX requests made.

This is tested on Chrome Dev 61 on Windows 10 and macOS.

Otherwise, this is almost perfection! :)

**Comment by qooob** [comment]
Mohamed, hi!

Thank you for your comments. I'm aware of those problems. At the moment, I need to find out how to get progressive output using jQuery.

There are other issues with File Manager and ConfigServer Security & Firewall modules. They don't work as SPA yet. There is so much code to review/rewrite.

I'm working on it ..

I'm looking forward (eager really) to start enrolling new features but I'm stuck with this stuff. (but I find this vital, so I'm not really complaining.. just has to be done..)

**Comment by tpnsolutions** [comment]
Another cosmetic issue I just discovered in RC1.

When you create a "Virtual Server", the left and right sidebars disappear.

**Comment by qooob** [comment]
You mean you are taken to the separate page? Well yes, RC1 doesn't have progressive output support.

Thanks Peter for looking into it.

**Comment by qooob** [comment]
#### RC Release Notes:
##### Version 19.00-RC2 (July 31, 2017)
* Added support for proressive output (buffered header)
* Added system information is now being recollected using native `recollect.cgi` script
* Fixed theme post save actions to refresh navigation menu properly on server request
* Fixed failed to load modules that can accept multiple methods, for example _Command Shell_
* Fixed navigation menu detection for module configuration pages
* Fixed pie-chart displayed incorrectly after going to theme's settings [#825](https://github.com/qooob/authentic-theme/issues/825)
* Fixed time displayed incorrectly on _System Information_ page [#825](https://github.com/qooob/authentic-theme/issues/825)

[Download and install ..](https://github.com/qooob/authentic-theme/releases/download/19.00-RC2/authentic-theme-19.00-RC2.wbt.gz)

**Comment by tpnsolutions** [comment]
**# 19.00-RC2**

*** This is just a cosmetic issue, likely an oversight and pretty minor. ***

When you click "Logs and Reports > Apache Error Log" the left navigation highlights "Apache Access Log".

*** This is just a cosmetic issue, likely a simple fix ***

When you click "Logs and Reports > Apache Access Log", the page show a clean, themed log entry text area.

![on-load view-logs](https://user-images.githubusercontent.com/4305218/28795692-aa58b03a-75ef-11e7-9ac7-ed6432a90100.png)

However, when you click the "refresh" button on the page, it seems to lose it's styling.

![on-refresh view-logs](https://user-images.githubusercontent.com/4305218/28795703-b65dafa2-75ef-11e7-8a50-5c719dbfe9c1.png)

*** This is a possible improvement to the "Logs and Reports" area ***

Instead of having to "manually" refresh the pages, wouldn't it be nifty to have say a "start" and "pause" button where you could asynchronously refresh the log in near real-time similar to issuing a "tail -f" on the command line. The purpose of having a "start" and "pause" button is so people can still decide whether they want to monitor the log, or simply see the last X amount of lines.

**Comment by qooob** [comment]
Yes, I like this idea so much. I will add this toggle. .. and fix the bug..

..please, please - keep digging. I need it.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Tantawi** [comment]
Great progress! thanks a lot. One cosmetic bug in RC2, Chrome v61 on Windows 10:

1- My server is running Ubuntu 16.04 and I have installed smartmontools package (to display hard drive temps on dashboard, I have three).
2- Upon login, or manual page refresh on the dashboard, "Drive temperatures" will flash for a split second then disappear.
3- Clicking the Dashboard icon from the navigation will make Drive temperatures display and stick, as normal.

**Comment by qooob** [comment]
Thanks, I will fix it all in RC3.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Tantawi** [comment]
One more error: Trying to set auto checking for packages updates to every hour, entering an email for reporting, and choosing "Install any updates", then clicking "Save" outputs a lot of errors in the console and nothing is saved.

**Comment by qooob** [comment]
Thanks @Tantawi I will take a look! :wink:

**Comment by qooob** [comment]
_RC3_ is available. Please give it a try!

@tpnsolutions Peter, new features with log auto-update will be enrolled later. It's on my to-do.

**Comment by qooob** [comment]
Nothing to add or say about _RC3_? :wink:

**Comment by tpnsolutions** [comment]
@qooob just installed RC3.

Started to navigate to each of the pages in the UI, and came across the first bug.

"Webmin > Others > File Manager" takes you to a "separate page" without the basic UI wrapped around it.

**Comment by tpnsolutions** [comment]
@qooob another bug, related to former.

"Virtualmin > Edit Web Content" opens in "new tab" and "separate page" without basic UI wrapped around it.

*** underlying issue appears to be related to "Filemin" integration ***

**Comment by tpnsolutions** [comment]
@qooob another bug found.

"Virtualmin > Logs and Reports > Apache Error Log" triggers "Apache Access Log" to be highlighted in left menu instead of "Apache Error Log".

**Comment by tpnsolutions** [comment]
@qooob another bug, related to former.

"Virtualmin > Services > Configure Website for SSL" triggers "Configure Website" to be highlighted in left menu instead of "Configure Website for SSL".

**Comment by qooob** [comment]
Thanks, Peter. File Manager is still not working in RC3.

About Error Log not being highlighted - confirmed.

**Comment by gnadelwartz** [comment]
when do you expect to have a working filemanager?

**Comment by qooob** [comment]
I'm working on it right now. 😉

_Sent from my HTC MSM8996 for arm64 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by qooob** [comment]
I'm working on it right now. 😉

_Sent from my HTC MSM8996 for arm64 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by qooob** [comment]
#### Version 19.00-RC4 is out (August 31, 2017).
* Added history native API support
* Added support for _File Manager_
* Added support for _ConfigServer Security & Firewall_ (in separate tab [so far](https://forum.configserver.com/viewtopic.php?f=5&t=10414&p=28609#p28589))
* Added _Virtual Server Summary_ link for _Virtualmin_
* Fixed all modules opened in single frame to have no offset and padding
* Fixed _HTTP Tunnel_	module to work correctly
* Fixed bugs [#53082](https://www.virtualmin.com/node/53082) [#53174](https://www.virtualmin.com/node/53174)

Please give it a try. Looking forward for your comments.

   _* Note: _RHEL_ and _FreeBSD_ complained about cache on my machines._

**Comment by qooob** [comment]
#### Version 19.00-RC5 (September 01, 2017)
* Fixed upcoming bugs

**Comment by Tantawi** [comment]
Thanks for the updated release. One bug in RC5:

- Click "Refresh Modules", it works but the left menu disappears with only a spinning loading icon. (Chrome Dev 62 and Firefox 56 on macOS)

**Comment by qooob** [comment]
That is strange as I couldn't reproduce it.

Could you please hard reload Chrome's cache and try again?

**Comment by Tantawi** [comment]
I did, same result. Also tried an incognito window, same. My server is running Ubuntu 16.04.3

Oh, I am running webmin behind an Apache proxy... can this cause it?

**Comment by qooob** [comment]
Oh, yes. It could. I just fixed proxy bug for RC6. I will check, now it's clear, thanks.

**Comment by Tantawi** [comment]
Thanks, I remember for the brief moment RC4 was available, I had this bug widely in every page :) but it was fixed quickly with RC5.

**Comment by gnadelwartz** [comment]
Ah, then I wait until RC6 ;-)


Am 4. September 2017 1:50:37 Nachm. schrieb Ilia Rostovtsev 
<notifications@github.com>:

**Comment by qooob** [comment]
[RC6](https://github.com/qooob/authentic-theme/releases/download/19.00-RC6/authentic-theme-19.00-RC6.wbt.gz) fixes all found bugs related to proxy configurations.

Please give it a try.

**Comment by Tantawi** [comment]
Just did with emptied cache, still have the exact issue with menu when refreshing the modules, and now another bug: The default Roboto font is not loading, instead everything is displayed in a Serif font. Other font options work fine though, just not the default.

I noticed you fixed another bug with refreshing the system information page, thanks! 👍

**Comment by qooob** [comment]
Oh, right. I see the cause of the issue with fonts. My compiler deleted its lib. WIll be fixed in RC7.

I can't reproduce _Refresh Modules_ bug. It woks fine on all systems, have a look:

[Video-screencast](https://rostovtsev.ru/pub/src/authentic/19.00-RC6/working_refresh_modules_link.webm)

I would need more info in case it still fails to work. Open console in Chrome. What's it showing?

**Comment by Tantawi** [comment]
hmm, the console looks fine:

GET https://xxxxx/unauthenticated/css/fonts-roboto.min.css?1900RC6 net::ERR_ABORTED
bundle.min.js?1900RC6:116 Running authentic.js - LEFT
bundle.min.js?1900RC6:116 Welcome to Authentic Theme 19.00-RC6
https://github.com/qooob/authentic-theme

One more comment about the 404 error on the css file, I get a lot of other 404 errors on the login page as well making it looks broken, but i can still login:

bootstrap.min.css?1900RC6
fontbase.min.css?1900RC6
authentic.min.css?1900RC6
fonts-roboto.min.css?1900RC6
jquery.min.js?1900RC6

Any specific info I can provide that might help debugging the other issue? I only have access to browsers on macOS now but will have Windows access in a few hours.

**Comment by qooob** [comment]
#### Version 19.00-RC7 (September 05, 2017)
* Fixed issue with missing dependencies on login page


I have fixed issues with missing dependencies in [RC7](https://github.com/qooob/authentic-theme/releases/download/19.00-RC7/authentic-theme-19.00-RC7.wbt.gz).

Anyone reading this, can you confirm _Refresh Modules Link_ causes navigation menu loading without stop?

**Comment by qooob** [comment]
@Tantawi Try going to Theme Settings, then _Force Update Theme_ and then install manually the downloaded package of RC7.

What your server OS?

**Comment by Tantawi** [comment]
Thanks for the rc7.

I did what you have suggested, no difference, still have the issue.

Server OS is Ubuntu 16.04.3 + 4.13 Kernel (but I just upgraded now from 4.12.10 it was the same).

Few things that might help:
- I have some modules disabled (like Java File Manager).
- I have renamed "MySQL Server" module to "MariaDB Server".
- I have no browser extensions installed.

**Comment by Tantawi** [comment]
I just tried to access webmin directly without the apache Proxy, (ip:port), and the issue remain...

**Comment by qooob** [comment]
What happens if you run `update_navigation_menu(-1)`

**Comment by qooob** [comment]
I've just updated [RC7](https://github.com/qooob/authentic-theme/releases/download/19.00-RC7/authentic-theme-19.00-RC7.wbt.gz), re-download/install please and try again.

It might fix your issue.

**Comment by Tantawi** [comment]
The updated RC7 still have same issue. Running the command you posted in the console made the menu text turns to a spinner (produced the bug) and gave me this in the console:

> update_navigation_menu(-1)
undefined

**Comment by Tantawi** [comment]
@tpnsolutions Can you please share your experience refreshing the modules in the latest RC7 to see wether you have the same bug as mine or if it is an isolated issue? much appreciated.

**Comment by qooob** [comment]
Hi,

I just released [RC8](https://github.com/qooob/authentic-theme/releases/download/19.00-RC8/authentic-theme-19.00-RC8.wbt.gz), try it guys.

@Tantawi Please try to share debugging info, from Network tab of the console in case it still doesn't work for you. I couldn't reproduce it on any of my machines (4+).

**Comment by gnadelwartz** [comment]
Hi, now I found time to test RC9. In the first place main things seems to work.
Somtimes it takes long to load a module for first time, but all my mainly used modules seems to work.

So far I found only two Issues in the reworked majordomo module:

- the global `configuration button` circles forever and edit_global.cgi is not loaded.
- the red loading indicator also stay forever
- the edit icon on the main screen is not shown anymore, only the edit textlink for non authentic themes. here is the code I used to replace the edit textlink with an icon if authentic theme is used:

```
print "<script>",
        "f__lnk_t_btn(['/majordomo/', '/majordomo/index.cgi'], 'table tbody td',",
        " 'a[href*=\"edit_info.cgi?\"], a[href*=\"edit_members.cgi?\"], a[href*=\"edit_subs.cgi?\"],",
                " a[href*=\"edit_mesg.cgi?\"]',",
                " 'btn btn-transparent btn-xs vertical-align-top margined-top-2', 'fa-edit');",
        "document.querySelectorAll('tbody td .btn.btn-transparent').forEach(function(button) {",
                " button.innerHTML=button.innerHTML.replace(/<\\/i>.*edit/,'');});",
        "</script>",
        "<style>.btn.btn-transparent { padding: 0 !important; color: grey;}</style>";
```
I know, this should be done by theme ... I'll be glad if you can do it in 19.0+
BTW: If I disable the above code, the redloading indication works, but global config not.

majordomo with with regular authentic theme:

![majordomo original](https://user-images.githubusercontent.com/4593242/30209184-17b6f0ae-9497-11e7-92a6-ea4859a9c05a.png)

majordomo with RC9

![majordomo rc9](https://user-images.githubusercontent.com/4593242/30209206-31112fc4-9497-11e7-82cb-12efd912f8c4.png)

**Comment by qooob** [comment]
What does this configuration button do? Is it stray button outside of the form element, meant to submit the form?

Where can I install this module from to test it?

**Comment by gnadelwartz** [comment]
the config button is a seperate form calling simply edit_global.cgi, soory to forget to attach the picture already taken:
![bildschirmfoto vom 2017-09-08 12-53-19](https://user-images.githubusercontent.com/4593242/30210089-4cec9b4e-949b-11e7-9e22-4039ce6798f8.png)

the reworked majordomo modul is a standard webmin module, but not installed in the standard distribution.


Description | Create and configure mailing lists for Majordomo version 1.94.
-- | --
Download | http://www.webmin.com/webmin/download/modules/majordomo.wbm.gz
Website | http://www.webmin.com/webmin/standard.html
Author | Jamie Cameron
Last updated | 2017-06-25 23:32:19

**Comment by Tantawi** [comment]
I found a bug with RC9 I think it is related to proxy config:

Go to Webmin Configuration --> Module Titles --> Try to rename any module and click "Save", I got a red error popup with this details:

> Request URL:
> https://.../webmin/edit_descs.cgi?xnavigation=1...save_descs.cgi

> Server response: 
> 404/"error"

> Response details: 
> error: Error - File not found 

> Server OS: 
> Ubuntu Linux 16.04.3

> User agent: 
> Google Inc./Mozilla/Netscape/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 > (KHTML, like Gecko) Chrome/63.0.3213.3 Safari/537.36; cookieEnabled

Then If I click to return to Webmin configuration I move to this URL in the browser:

https://proxyURL/webmin/:10000/webmin/?xnavigation=1

Which works fine though. And the module is actually renamed as well.

Regarding my specific menu bug with forever loading I think you can ignore it as no one else have reported it, it might be my server though all XHR requests are finished with code 200 and no errors in console or anything. Really weird.

**Comment by qooob** [comment]
Hi, I just tested it in [RC10](https://github.com/qooob/authentic-theme/releases/download/19.00-RC10/authentic-theme-19.00-RC10.wbt.gz) and I don't see this happening.

Please upgrade, force-clear cache and try again.

**Comment by Tantawi** [comment]
Just tried RC10, same thing, confirmed that it only happens if I access webmin via Apache proxy, as direct access works fine without error message.

Update: So I had ProxyPreserveHost set to On on my Apache config, tried Off and it solved the issue. :)

**Comment by qooob** [comment]
Good to know that it's solved. I couldn't reproduce it on my proxy setup.

**Comment by qooob** [comment]
Peter, I will add the requested functionality (about automatic log refresh using timeout) to final release of version 19.00 very soon.

This is how the page is going to look like.

![screenshot from 2017-09-23 09-28-24](https://user-images.githubusercontent.com/4426533/30770827-d2910868-a042-11e7-9410-bdacdcde3f58.png)

[Video-screencast](https://rostovtsev.ru/pub/src/authentic/19.00/refreshing_log_page_with_timeout.webm).

**Comment by gnadelwartz** [comment]
Hi,

RC10 works now like a charm: It's fast and stable :-)

Only the problem with my Majordomo Config Button cycling forever remains.
In case you did not get my anser to your PN:

I have a link to download majordomo in  config dialog of the module (first aid section), its a working majordomo with all oatches applied.

Direct link: http://files1.directadmin.com/services/es_7.0_64/majordomo-1.94.5-patched.tar.gz

The module I'M using is from the official repository:

Description | Create and configure mailing lists for Majordomo version 1.94.
Download | http://www.webmin.com/webmin/download/modules/majordomo.wbm.gz
Website | http://www.webmin.com/webmin/standard.html
Author | Jamie Cameron
Last updated | 2017-06-25 23:32:19

**Comment by qooob** [comment]
Kay, I remember about your request. Your email is staying marked in my inbox. I will do it before the initial release or at most in 19.01. :wink:

**Comment by gnadelwartz** [comment]
anything new? e.g. RC11?

**Comment by qooob** [comment]
Doing final release within 4 hours. Later comeback to the smaller issues. So much to do!

**Comment by gnadelwartz** [comment]
sounds good! thanks for your work!
If you ever visit germany I have to spend you a beer (wine/whisky) or two!

**Comment by qooob** [comment]
I would love to. Thanks. :wink:

**Comment by qooob** [comment]
Version 19.00 is finally released. :sparkles:  

Enjoy.

**Comment by Zen4All** [comment]
🎆 Awesome. I have been following this in surveillance mode, but I really appreciate all the effort you put in to this.

**Comment by qooob** [comment]
Well, thank you for your kind words.

**Comment by 7starsone** [comment]
Hello, when will the update be available on the System Information page? Thanks

**Comment by qooob** [comment]
A bit later. Just force update from theme settings.

**Comment by 7starsone** [comment]
first issue on navigation
example: click on **Webmin→Servers→Dovecot...**
at this point, if you click on **System→Log File Rotation...**
it remains on the Dovecot page, it doesn't change page

**Comment by 7starsone** [comment]
i get this on console:
`POST https://mydomain.com:10000/logrotate/ net::ERR_CONNECTION_RESET`

**Comment by qooob** [comment]
I can not reproduce this. It works for me as expected. Do you have console opened or closed when you were testing it? (just asking)

What is your system information for server and client?

**Comment by 7starsone** [comment]
also cleared cache, logged out... it's the same
Server CentOS 7.3.1611 64bit
Client Windows 10, Chrome 61.0.3163.100 64bit, no matter if you keep the console open or closed...

**Comment by 7starsone** [comment]
something else I've noticed in this case...
on the center page, if i'm on a Dovecot button (eg. **SSL Configuration**), it retrieves the URL from the Log Rotate module but the viewed page is from Dovecot....

```
<div class="col-xs-1 icons-container forged-xx-skip grayscaled animated" data-original-title="" title=""><a href="edit_ssl.cgi" class="icon_link" data-title="" data-toggle="tooltip" data-placement="auto bottom" data-container="body" data-original-title="" title=""><img class="ui_icon ui_icon_protected" src="/images/modules/dovecot/ssl.gif" alt=""><br>SSL Configuration</a>
</div>
```
here it becomes `https://mydomain.com:10000/logrotate/edit_ssl.cgi`
so still a little fuzzy

**Comment by qooob** [comment]
I have three different, physical machines with different OSes and browsers. I can not reproduce it.

Can anyone else reading it reproduce it? Please be kind giving new release a try.

**Comment by qooob** [comment]
@7starsone Try in incognito mode please.

**Comment by 7starsone** [comment]
in incognito it works, in normal mode, instead, it doesn't work as expected even if all extensions are disabled

**Comment by 7starsone** [comment]
maybe a problem with cookies?

**Comment by qooob** [comment]
I non-incognito mode, open console and then hold refresh button, then select 3 option. Does it help?

**Comment by 7starsone** [comment]
ok, it's a cookie issue. Guys, if you update from the 18.49...

you need to clear all cache and cookies from browser, otherwise you have this issue

**Comment by qooob** [comment]
@7starsone I'm glad it helped but i don't think it has anything to do with cookies itself but rather, it's the cache issue.

**Comment by 7starsone** [comment]
please, take a look at https://github.com/virtualmin/virtualmin-gpl/issues/16
thanks

**Comment by qooob** [comment]
@gnadelwartz Speaking about your non-submitting form. It's required to be fixed on the Perl side.

Make sure that the form contains the actual button. There is a fix for crazy forms/buttons but it doesn't cover all cases, and actually shouldn't.

You could refer to the following commits that fixes exactly the same problem for other modules.

https://github.com/webmin/webmin/pull/644/commits/344819f1ce3476035ff6d0637fd36cc415b934e5
https://github.com/webmin/webmin/pull/645/commits/344819f1ce3476035ff6d0637fd36cc415b934e5

**Comment by gnadelwartz** [comment]
ill have a look

**Comment by gnadelwarty** [comment]
found the problem https://github.com/webmin/webmin/pull/651
