### ISSUE TITLE
Bootup and Shutdown module is broken

### ISSUE THREAD

**Issue by matrix200** [qooob/authentic-theme#928]
It is no longer possible to edit init scripts using the module.
Steps to reproduce:
1. Open Bootup and Shutdown module (under system).
2. Click on any upstart click from the list
Result:
The following screen is displayed and it is impossible to edit the script in anyway.
See attached screenshot:
![screenshot](https://user-images.githubusercontent.com/806758/33804636-a07f277c-ddb1-11e7-9011-7e50722837a8.jpg)

Server side OS: Centos 6.9
Client side: Windows 7x64, browser Palemoon 27.6.2 (32bit).

**Comment by qooob** [comment]
I can confirm that content is empty.

Very surprising. I will double-check why this is happening.

Thank you for reporting.

**Comment by qooob** [comment]
I found the cause of the issue.

**Comment by qooob** [comment]
Will be fixed accordingly.

**Comment by matrix200** [comment]
That was quick :)

**Comment by matrix200** [comment]
I think its prudent to release a small webmin update for that issue.
Jamie should probably be informed about this as well.

**Comment by qooob** [comment]
It's caused by third-party library that needs to be fixed to make it work with Webmin expectations.

----

P.S. I remember about your SysStat question, I just don't have much to say right now. I will get back to that issue later.

**Comment by matrix200** [comment]
Sure, no pressure on that one.

**Comment by qooob** [comment]
It's fixed in
https://github.com/qooob/authentic-theme/commit/2175a3abaf2ff293f0c46d3dd4945f0c84397052

Please give it a try.

**Comment by matrix200** [comment]
I have replaced the two changed files from that branch and the problem is still there.

**Comment by qooob** [comment]
You need to make sure that you clear browser's cache and reload the page/theme.

**Comment by matrix200** [comment]
OK sorry, I had to force reload in browser.
That problem is now solved, but your fix broke a bunch of other stuff.
Namely all the icons are missing 
Let me attach a screenshot

**Comment by qooob** [comment]
Just go to theme's settings and run force upgrade with development version.

**Comment by matrix200** [comment]
Now it works :)

**Comment by qooob** [comment]
👍

**Comment by matrix200** [comment]
Edit action is fixed and the webmin is back to normal.

**Comment by matrix200** [comment]
Like I said, I think its a good idea to inform Jamie and possibly release and updated webmin version.
Otherwise, there will be alot of complaints about that.

**Comment by harms916** [comment]
I just noticed today that the Edit Action on the Bootup and Shutdown works on some of the services but on others it still loads the blank page as descibed above. 
Running Ubuntu 14.04, Webmin 1.87, Authentic Theme version 19.04 and when I try and edit the apparmor, dns-clean, grub-common, halt, webmin  service and unifi I still get the blank page. 
If you change the theme to the default it works as expected.

**Comment by qooob** [comment]
Yes. 19.04 is affected. Please Force update to the latest using theme configuration page and Force update theme option.

**Comment by harms916** [comment]
Beautiful. That did the trick. Thanks
